### PR TITLE
Fixed typos and weird grammar

### PR DESCRIPTION
**Pull request by michu97736**
I made some weird sentences easier to understand and fixed grammar and case errors. I hope I didn't break anything.

### CODE REVIEW

**Comment by piotrulos** [comment]
Some of the changes conflicts with internal version (because some of the stuff are getting rewritten)

**Comment by michu97736** [comment]
Could you tell what I need to change?

**Comment by piotrulos** [comment]
It's hard to tell now since I'm redoing mod updates to simplify it, and some stuff related to mwc. I think best way would be wait until that update is pushed, and then you can re-create this PR.

**Comment by michu97736** [comment]
sure, thanks!

**Pull request closed without merging**
