### PR TITLE
Update to newer .Net Runtime & Fix on Mono w/out Wine

### PR DESCRIPTION
**Pull request by Krutonium**
It stopped working on Wine for me out of nowhere, so I ran it directly in Mono, and experienced numerous issues, mostly to do with the slashes being the wrong direction, which doesn't matter on Windows, but *does* matter on Linux and MacOS. I corrected that, then ran into an issue with Ionic.zip, which prompted me to remove it, upgrade the .Net version to 4.5, and use the built in .zip file handling, which is cleaner imho.

### CODE REVIEW

**Comment by yasink21** [comment]
hey there, I am having trouble running this on Wine as well, could you provide me with the patched version of yours?

Thanks

**Comment by piotrulos** [comment]
4.5 will break compatibility with older OS versions, can't accept that change.

**Comment by Krutonium** [comment]
Which OS's are you looking to maintain compatibility with?

**Comment by piotrulos** [comment]
.net 4.0 is max, because suprisingly or not there are XP and vista users for mscloader.

**Comment by piotrulos** [comment]
also seen windows 2003 in stats.

**Comment by Krutonium** [comment]
Wine reports XP by default a lot of the time, are you sure it's not that? Regardless, I'll have to think of an alternative then - The zip library you're using seems to be broken on Mono.

[MSCPatcherLinux.zip](https://github.com/piotrulos/MSCModLoader/files/4560752/MSCPatcher.zip)
@yasink21 Replace the normal exe with this and run with Mono

**Comment by piotrulos** [comment]
OS is reported by unity, and since you can just run native binary for linux it reports itself as linux not wine.
So yeah there are few hundred legit players below win7.

**Comment by Krutonium** [comment]
Except that nobody really uses the Native Binary because it works better in wine *anyway*. The native executable has broken transparency.

**Comment by piotrulos** [comment]
I can just implement slashes from this PR, because it doesn't matter in windows, but will not change the runtime version.
Besides old OS compatibility 4.0 is also default for most OS, you need to manually update to 4.5 in anything below win8.1. 
People still fails to follow simple instructions to unpack before running installation, I don't expect them to follow instructions to install 4.5.

**Pull request closed without merging**
